name: learn_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  pinput: ^4.0.0
  country_picker: ^2.0.26
  flutter_staggered_grid_view: ^0.7.0
  firebase_remote_config: ^4.4.7
  flutter_svg: any
  google_sign_in: ^6.2.1
  firebase_database: ^10.5.7
  loading_animation_widget: ^1.2.1
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  file_picker: ^8.0.3
  flick_video_player: ^0.8.0
  video_player: ^2.8.6
  audioplayers: ^6.0.0
  audio_video_progress_bar: ^2.0.3
  path_provider: ^2.1.3
  pdfx: ^2.6.0
  internet_file: ^1.2.0
  firebase_admin: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
