// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeDPVNiFbrhUi4URg-9idvQHOeQOqZ8_o',
    appId: '1:505721694279:web:2934bb01e32280afb36962',
    messagingSenderId: '505721694279',
    projectId: 'learn-firebase-cb67a',
    authDomain: 'learn-firebase-cb67a.firebaseapp.com',
    storageBucket: 'learn-firebase-cb67a.appspot.com',
    measurementId: 'G-W4058XY9BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWCHcEBfscRl5bGatHk0YfdJYdAubkbsQ',
    appId: '1:505721694279:android:ad702ea051bccabcb36962',
    messagingSenderId: '505721694279',
    projectId: 'learn-firebase-cb67a',
    storageBucket: 'learn-firebase-cb67a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD32n6fe6QO0SjrlbmC4gH2BIRSkBZRCSQ',
    appId: '1:505721694279:ios:2bda9d0528144b1db36962',
    messagingSenderId: '505721694279',
    projectId: 'learn-firebase-cb67a',
    storageBucket: 'learn-firebase-cb67a.appspot.com',
    iosBundleId: 'com.example.learnFirebase',
  );
}
